#!/bin/bash
# Setup dnsmasq for OpenShift cluster DNS

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../config/cluster-vars.sh"

CONFIG_FILE="/etc/dnsmasq.d/${CLUSTER_NAME}.conf"

echo "Setting up dnsmasq for ${CLUSTER_DOMAIN}"

# Generate dnsmasq configuration
cat > /tmp/${CLUSTER_NAME}-dnsmasq.conf <<EOF
# OpenShift cluster DNS: ${CLUSTER_DOMAIN}
# Generated by openshift-the-hard-way

# Don't forward short names
domain-needed
bogus-priv

# Local domain
local=/${CLUSTER_DOMAIN}/
domain=${CLUSTER_DOMAIN}

# API endpoint (points to VIP, which HAProxy load balances)
address=/api.${CLUSTER_DOMAIN}/${API_VIP}
address=/api-int.${CLUSTER_DOMAIN}/${API_VIP}

# Wildcard for apps (ingress)
address=/.apps.${CLUSTER_DOMAIN}/${INGRESS_VIP}

# Bootstrap node
address=/${BOOTSTRAP_NAME}.${CLUSTER_DOMAIN}/${BOOTSTRAP_IP}

# Master nodes
address=/${MASTER0_NAME}.${CLUSTER_DOMAIN}/${MASTER0_IP}
address=/${MASTER1_NAME}.${CLUSTER_DOMAIN}/${MASTER1_IP}
address=/${MASTER2_NAME}.${CLUSTER_DOMAIN}/${MASTER2_IP}

# Worker nodes
address=/${WORKER0_NAME}.${CLUSTER_DOMAIN}/${WORKER0_IP}
address=/${WORKER1_NAME}.${CLUSTER_DOMAIN}/${WORKER1_IP}

# etcd nodes (same as masters)
address=/etcd-0.${CLUSTER_DOMAIN}/${MASTER0_IP}
address=/etcd-1.${CLUSTER_DOMAIN}/${MASTER1_IP}
address=/etcd-2.${CLUSTER_DOMAIN}/${MASTER2_IP}

# SRV records for etcd
# Format: _service._proto.name TTL class SRV priority weight port target
srv-host=_etcd-server-ssl._tcp.${CLUSTER_DOMAIN},etcd-0.${CLUSTER_DOMAIN},2380,0,10
srv-host=_etcd-server-ssl._tcp.${CLUSTER_DOMAIN},etcd-1.${CLUSTER_DOMAIN},2380,0,10
srv-host=_etcd-server-ssl._tcp.${CLUSTER_DOMAIN},etcd-2.${CLUSTER_DOMAIN},2380,0,10
EOF

echo "Generated configuration:"
cat /tmp/${CLUSTER_NAME}-dnsmasq.conf
echo ""

# Install configuration
echo "Installing to ${CONFIG_FILE}"
sudo cp /tmp/${CLUSTER_NAME}-dnsmasq.conf "${CONFIG_FILE}"
rm /tmp/${CLUSTER_NAME}-dnsmasq.conf

# Check dnsmasq syntax
echo "Checking dnsmasq configuration..."
if dnsmasq --test; then
    echo "Configuration syntax OK"
else
    echo "Configuration syntax error!"
    exit 1
fi

# Restart dnsmasq
echo "Restarting dnsmasq..."
sudo systemctl enable dnsmasq
sudo systemctl restart dnsmasq

echo ""
echo "dnsmasq configured successfully"
echo ""
echo "IMPORTANT: Configure your host to use this DNS server"
echo "Add to /etc/resolv.conf or NetworkManager:"
echo "  nameserver ${DNS_SERVER}"
