#!/bin/bash
# Setup HAProxy load balancer for OpenShift cluster

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/../../config/cluster-vars.sh"

CONFIG_FILE="/etc/haproxy/haproxy.cfg"

echo "Setting up HAProxy for ${CLUSTER_DOMAIN}"

# Backup existing config if present
if [[ -f "${CONFIG_FILE}" ]]; then
    sudo cp "${CONFIG_FILE}" "${CONFIG_FILE}.bak.$(date +%Y%m%d%H%M%S)"
fi

# Generate HAProxy configuration
cat > /tmp/haproxy-${CLUSTER_NAME}.cfg <<EOF
# OpenShift HAProxy configuration
# Generated by openshift-the-hard-way

global
    log /dev/log local0
    chroot /var/lib/haproxy
    pidfile /var/run/haproxy.pid
    maxconn 4000
    user haproxy
    group haproxy
    daemon
    stats socket /var/lib/haproxy/stats

defaults
    mode tcp
    log global
    option tcplog
    option dontlognull
    option redispatch
    retries 3
    timeout queue 1m
    timeout connect 10s
    timeout client 1m
    timeout server 1m
    timeout check 10s
    maxconn 3000

# Stats page
listen stats
    bind *:9000
    mode http
    stats enable
    stats uri /stats
    stats refresh 10s
    stats admin if LOCALHOST

# Kubernetes API Server
# During bootstrap: traffic goes to bootstrap + masters
# After bootstrap: remove bootstrap from pool
frontend kubernetes-api
    bind *:6443
    default_backend kubernetes-api-backend

backend kubernetes-api-backend
    balance roundrobin
    option httpchk GET /readyz HTTP/1.0
    http-check expect status 200
    # Bootstrap (remove after cluster is up)
    server ${BOOTSTRAP_NAME} ${BOOTSTRAP_IP}:6443 check
    # Masters
    server ${MASTER0_NAME} ${MASTER0_IP}:6443 check
    server ${MASTER1_NAME} ${MASTER1_IP}:6443 check
    server ${MASTER2_NAME} ${MASTER2_IP}:6443 check

# Machine Config Server
# Used during node boot to fetch ignition config
frontend machine-config-server
    bind *:22623
    default_backend machine-config-server-backend

backend machine-config-server-backend
    balance roundrobin
    # Bootstrap (serves during bootstrap phase)
    server ${BOOTSTRAP_NAME} ${BOOTSTRAP_IP}:22623 check
    # Masters (serve after pivot)
    server ${MASTER0_NAME} ${MASTER0_IP}:22623 check
    server ${MASTER1_NAME} ${MASTER1_IP}:22623 check
    server ${MASTER2_NAME} ${MASTER2_IP}:22623 check

# Ingress HTTP
frontend ingress-http
    bind *:80
    default_backend ingress-http-backend

backend ingress-http-backend
    balance roundrobin
    option httpchk GET /healthz/ready HTTP/1.0
    http-check expect status 200
    # Workers (or masters in compact cluster)
    server ${WORKER0_NAME} ${WORKER0_IP}:80 check
    server ${WORKER1_NAME} ${WORKER1_IP}:80 check

# Ingress HTTPS
frontend ingress-https
    bind *:443
    default_backend ingress-https-backend

backend ingress-https-backend
    balance roundrobin
    option httpchk GET /healthz/ready HTTP/1.0
    http-check expect status 200
    # Workers (or masters in compact cluster)
    server ${WORKER0_NAME} ${WORKER0_IP}:443 check
    server ${WORKER1_NAME} ${WORKER1_IP}:443 check
EOF

echo "Generated configuration:"
cat /tmp/haproxy-${CLUSTER_NAME}.cfg
echo ""

# Check syntax
echo "Checking HAProxy configuration syntax..."
if haproxy -c -f /tmp/haproxy-${CLUSTER_NAME}.cfg; then
    echo "Configuration syntax OK"
else
    echo "Configuration syntax error!"
    exit 1
fi

# Install configuration
echo "Installing to ${CONFIG_FILE}"
sudo cp /tmp/haproxy-${CLUSTER_NAME}.cfg "${CONFIG_FILE}"
rm /tmp/haproxy-${CLUSTER_NAME}.cfg

# Enable and restart HAProxy
echo "Restarting HAProxy..."
sudo systemctl enable haproxy
sudo systemctl restart haproxy

echo ""
echo "HAProxy configured successfully"
echo ""
echo "Stats available at: http://localhost:9000/stats"
echo ""
echo "IMPORTANT: After cluster is bootstrapped, remove bootstrap from API backend"
